### ISSUE TITLE
Funcionamento e homologação

### ISSUE THREAD

**Issue by maracaipe** [willkerms/CNAB#1]
Olá @willkerms, parabéns pelo projeto.

Estou com um projeto no qual preciso gerar remessa para os bancos bradesco e sicoob, por isso me interessei no seu repo.
Vi que a remessa e retorno do bradesco *aparentemente* estão completos e do sicoob somente a remessa. A remessa dos bancos já teve a homologação?

**Comment by willkerms** [comment]
Bom dia, sim as remessas estão funcionando e estou utilizando esta biblioteca em um projeto privado.

Tenho um cliente que todos os dias envia remessas para os bancos Bradesco e Sicoob, desculpe não ter muita documentação ainda pois subi os projetos semana passada e ainda não tive tempo de organizá-los, e descreve-los.

Referente ao Sicoob tenho uma ressalva a lhe fazer, meu cliente utiliza uma cooperativa Sicoob que utiliza o sistema http://www.netsuprema.com.br/credisgpa/ então a remessa é enviada a este sistema NetSuprema. 

Irei renomear as classes do Sicoob para SicoobNetSuprema, e construir outras para o Sicoob Net Empresarial, pois tenho outro cliente que não utiliza o NetSuprema.

**Comment by maracaipe** [comment]
Ótimo.

Provavelmente não é compatível essa classe com o empresarial dá Sicoob, né?

Estou disposto a colaborar com o projeto pois também estou com uma demanda
importante de alguns clientes.

**Comment by willkerms** [comment]
Vou renomear as classes adicionar uma pasta de documentos e criar uma tag e te adiciono no projeto.
